# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envisproto/commons/id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envisproto/commons/id.proto',
  package='envisproto.commons',
  syntax='proto3',
  serialized_options=_b('\n ai.nimbleedge.envisproto.commons'),
  serialized_pb=_b('\n\x1b\x65nvisproto/commons/id.proto\x12\x12\x65nvisproto.commons\".\n\x02Id\x12\x10\n\x06id_int\x18\x01 \x01(\x03H\x00\x12\x10\n\x06id_str\x18\x02 \x01(\tH\x00\x42\x04\n\x02idB\"\n ai.nimbleedge.envisproto.commonsb\x06proto3')
)




_ID = _descriptor.Descriptor(
  name='Id',
  full_name='envisproto.commons.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_int', full_name='envisproto.commons.Id.id_int', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_str', full_name='envisproto.commons.Id.id_str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='id', full_name='envisproto.commons.Id.id',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=51,
  serialized_end=97,
)

_ID.oneofs_by_name['id'].fields.append(
  _ID.fields_by_name['id_int'])
_ID.fields_by_name['id_int'].containing_oneof = _ID.oneofs_by_name['id']
_ID.oneofs_by_name['id'].fields.append(
  _ID.fields_by_name['id_str'])
_ID.fields_by_name['id_str'].containing_oneof = _ID.oneofs_by_name['id']
DESCRIPTOR.message_types_by_name['Id'] = _ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'envisproto.commons.id_pb2'
  # @@protoc_insertion_point(class_scope:envisproto.commons.Id)
  ))
_sym_db.RegisterMessage(Id)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
