# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envisproto/tensors/shape.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envisproto/tensors/shape.proto',
  package='envisproto.tensors',
  syntax='proto3',
  serialized_options=_b('\n ai.nimbleedge.envisproto.tensors'),
  serialized_pb=_b('\n\x1e\x65nvisproto/tensors/shape.proto\x12\x12\x65nvisproto.tensors\"\x15\n\x05Shape\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\x42\"\n ai.nimbleedge.envisproto.tensorsb\x06proto3')
)




_SHAPE = _descriptor.Descriptor(
  name='Shape',
  full_name='envisproto.tensors.Shape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dims', full_name='envisproto.tensors.Shape.dims', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Shape'] = _SHAPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Shape = _reflection.GeneratedProtocolMessageType('Shape', (_message.Message,), dict(
  DESCRIPTOR = _SHAPE,
  __module__ = 'envisproto.tensors.shape_pb2'
  # @@protoc_insertion_point(class_scope:envisproto.tensors.Shape)
  ))
_sym_db.RegisterMessage(Shape)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
