# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envisproto/state/state_tensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fedrec.envisproto.tensors import torch_tensor_pb2 as envisproto_dot_tensors_dot_torch__tensor__pb2
from fedrec.envisproto.tensors import parameter_pb2 as envisproto_dot_tensors_dot_parameter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envisproto/state/state_tensor.proto',
  package='envisproto.state',
  syntax='proto3',
  serialized_options=_b('\n\036ai.nimbleedge.envisproto.state'),
  serialized_pb=_b('\n#envisproto/state/state_tensor.proto\x12\x10\x65nvisproto.state\x1a%envisproto/tensors/torch_tensor.proto\x1a\"envisproto/tensors/parameter.proto\"\x86\x01\n\x0bStateTensor\x12\x37\n\x0ctorch_tensor\x18\x01 \x01(\x0b\x32\x1f.envisproto.tensors.TorchTensorH\x00\x12\x34\n\x0btorch_param\x18\x02 \x01(\x0b\x32\x1d.envisproto.tensors.ParameterH\x00\x42\x08\n\x06tensorB \n\x1e\x61i.nimbleedge.envisproto.stateb\x06proto3')
  ,
  dependencies=[envisproto_dot_tensors_dot_torch__tensor__pb2.DESCRIPTOR,envisproto_dot_tensors_dot_parameter__pb2.DESCRIPTOR,])




_STATETENSOR = _descriptor.Descriptor(
  name='StateTensor',
  full_name='envisproto.state.StateTensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='torch_tensor', full_name='envisproto.state.StateTensor.torch_tensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torch_param', full_name='envisproto.state.StateTensor.torch_param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='tensor', full_name='envisproto.state.StateTensor.tensor',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=133,
  serialized_end=267,
)

_STATETENSOR.fields_by_name['torch_tensor'].message_type = envisproto_dot_tensors_dot_torch__tensor__pb2._TORCHTENSOR
_STATETENSOR.fields_by_name['torch_param'].message_type = envisproto_dot_tensors_dot_parameter__pb2._PARAMETER
_STATETENSOR.oneofs_by_name['tensor'].fields.append(
  _STATETENSOR.fields_by_name['torch_tensor'])
_STATETENSOR.fields_by_name['torch_tensor'].containing_oneof = _STATETENSOR.oneofs_by_name['tensor']
_STATETENSOR.oneofs_by_name['tensor'].fields.append(
  _STATETENSOR.fields_by_name['torch_param'])
_STATETENSOR.fields_by_name['torch_param'].containing_oneof = _STATETENSOR.oneofs_by_name['tensor']
DESCRIPTOR.message_types_by_name['StateTensor'] = _STATETENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateTensor = _reflection.GeneratedProtocolMessageType('StateTensor', (_message.Message,), dict(
  DESCRIPTOR = _STATETENSOR,
  __module__ = 'envisproto.state.state_tensor_pb2'
  # @@protoc_insertion_point(class_scope:envisproto.state.StateTensor)
  ))
_sym_db.RegisterMessage(StateTensor)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
