# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envisproto/execution/plan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envisproto.commons import id_pb2 as envisproto_dot_commons_dot_id__pb2
from envisproto.execution import type_wrapper_pb2 as envisproto_dot_execution_dot_type__wrapper__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envisproto/execution/plan.proto',
  package='envisproto.execution',
  syntax='proto3',
  serialized_options=_b('\n\"ai.nimbleedge.envisproto.execution'),
  serialized_pb=_b('\n\x1f\x65nvisproto/execution/plan.proto\x12\x14\x65nvisproto.execution\x1a\x1b\x65nvisproto/commons/id.proto\x1a\'envisproto/execution/type_wrapper.proto\"\xdd\x01\n\x04Plan\x12\"\n\x02id\x18\x01 \x01(\x0b\x32\x16.envisproto.commons.Id\x12\x15\n\rinclude_state\x18\x03 \x01(\x08\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x13\n\x0btorchscript\x18\x07 \x01(\x0c\x12<\n\x0binput_types\x18\x08 \x01(\x0b\x32\'.envisproto.execution.NestedTypeWrapper\x12\x16\n\x0e\x62\x61se_framework\x18\t \x01(\tB$\n\"ai.nimbleedge.envisproto.executionb\x06proto3')
  ,
  dependencies=[envisproto_dot_commons_dot_id__pb2.DESCRIPTOR,envisproto_dot_execution_dot_type__wrapper__pb2.DESCRIPTOR,])




_PLAN = _descriptor.Descriptor(
  name='Plan',
  full_name='envisproto.execution.Plan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='envisproto.execution.Plan.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_state', full_name='envisproto.execution.Plan.include_state', index=1,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='envisproto.execution.Plan.name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='envisproto.execution.Plan.tags', index=3,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='envisproto.execution.Plan.description', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torchscript', full_name='envisproto.execution.Plan.torchscript', index=5,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_types', full_name='envisproto.execution.Plan.input_types', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base_framework', full_name='envisproto.execution.Plan.base_framework', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=349,
)

_PLAN.fields_by_name['id'].message_type = envisproto_dot_commons_dot_id__pb2._ID
_PLAN.fields_by_name['input_types'].message_type = envisproto_dot_execution_dot_type__wrapper__pb2._NESTEDTYPEWRAPPER
DESCRIPTOR.message_types_by_name['Plan'] = _PLAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Plan = _reflection.GeneratedProtocolMessageType('Plan', (_message.Message,), dict(
  DESCRIPTOR = _PLAN,
  __module__ = 'envisproto.execution.plan_pb2'
  # @@protoc_insertion_point(class_scope:envisproto.execution.Plan)
  ))
_sym_db.RegisterMessage(Plan)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
