# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envisproto/execution/type_wrapper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envisproto/execution/type_wrapper.proto',
  package='envisproto.execution',
  syntax='proto3',
  serialized_options=_b('\n\"ai.nimbleedge.envisproto.execution'),
  serialized_pb=_b('\n\'envisproto/execution/type_wrapper.proto\x12\x14\x65nvisproto.execution\"(\n\x13InputTypeDescriptor\x12\x11\n\ttype_name\x18\x01 \x01(\t\"\x8b\x06\n\x11NestedTypeWrapper\x12K\n\x0cnested_types\x18\x01 \x01(\x0b\x32\x35.envisproto.execution.NestedTypeWrapper.TypeContainer\x1aI\n\x08TypeList\x12=\n\x0cnested_types\x18\x01 \x03(\x0b\x32\'.envisproto.execution.NestedTypeWrapper\x1aJ\n\tTypeTuple\x12=\n\x0cnested_types\x18\x01 \x03(\x0b\x32\'.envisproto.execution.NestedTypeWrapper\x1a\xbe\x01\n\x07TypeMap\x12V\n\x0cnested_types\x18\x01 \x03(\x0b\x32@.envisproto.execution.NestedTypeWrapper.TypeMap.NestedTypesEntry\x1a[\n\x10NestedTypesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.envisproto.execution.NestedTypeWrapper:\x02\x38\x01\x1a\xd0\x02\n\rTypeContainer\x12@\n\x0bnested_type\x18\x01 \x01(\x0b\x32).envisproto.execution.InputTypeDescriptorH\x00\x12L\n\x10nested_type_list\x18\x02 \x01(\x0b\x32\x30.envisproto.execution.NestedTypeWrapper.TypeListH\x00\x12N\n\x11nested_type_tuple\x18\x03 \x01(\x0b\x32\x31.envisproto.execution.NestedTypeWrapper.TypeTupleH\x00\x12K\n\x10nested_type_dict\x18\x04 \x01(\x0b\x32/.envisproto.execution.NestedTypeWrapper.TypeMapH\x00\x42\x12\n\x10nested_containerB$\n\"ai.nimbleedge.envisproto.executionb\x06proto3')
)




_INPUTTYPEDESCRIPTOR = _descriptor.Descriptor(
  name='InputTypeDescriptor',
  full_name='envisproto.execution.InputTypeDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_name', full_name='envisproto.execution.InputTypeDescriptor.type_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=105,
)


_NESTEDTYPEWRAPPER_TYPELIST = _descriptor.Descriptor(
  name='TypeList',
  full_name='envisproto.execution.NestedTypeWrapper.TypeList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested_types', full_name='envisproto.execution.NestedTypeWrapper.TypeList.nested_types', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=279,
)

_NESTEDTYPEWRAPPER_TYPETUPLE = _descriptor.Descriptor(
  name='TypeTuple',
  full_name='envisproto.execution.NestedTypeWrapper.TypeTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested_types', full_name='envisproto.execution.NestedTypeWrapper.TypeTuple.nested_types', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=355,
)

_NESTEDTYPEWRAPPER_TYPEMAP_NESTEDTYPESENTRY = _descriptor.Descriptor(
  name='NestedTypesEntry',
  full_name='envisproto.execution.NestedTypeWrapper.TypeMap.NestedTypesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='envisproto.execution.NestedTypeWrapper.TypeMap.NestedTypesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='envisproto.execution.NestedTypeWrapper.TypeMap.NestedTypesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=548,
)

_NESTEDTYPEWRAPPER_TYPEMAP = _descriptor.Descriptor(
  name='TypeMap',
  full_name='envisproto.execution.NestedTypeWrapper.TypeMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested_types', full_name='envisproto.execution.NestedTypeWrapper.TypeMap.nested_types', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NESTEDTYPEWRAPPER_TYPEMAP_NESTEDTYPESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=548,
)

_NESTEDTYPEWRAPPER_TYPECONTAINER = _descriptor.Descriptor(
  name='TypeContainer',
  full_name='envisproto.execution.NestedTypeWrapper.TypeContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested_type', full_name='envisproto.execution.NestedTypeWrapper.TypeContainer.nested_type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested_type_list', full_name='envisproto.execution.NestedTypeWrapper.TypeContainer.nested_type_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested_type_tuple', full_name='envisproto.execution.NestedTypeWrapper.TypeContainer.nested_type_tuple', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested_type_dict', full_name='envisproto.execution.NestedTypeWrapper.TypeContainer.nested_type_dict', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='nested_container', full_name='envisproto.execution.NestedTypeWrapper.TypeContainer.nested_container',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=551,
  serialized_end=887,
)

_NESTEDTYPEWRAPPER = _descriptor.Descriptor(
  name='NestedTypeWrapper',
  full_name='envisproto.execution.NestedTypeWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested_types', full_name='envisproto.execution.NestedTypeWrapper.nested_types', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NESTEDTYPEWRAPPER_TYPELIST, _NESTEDTYPEWRAPPER_TYPETUPLE, _NESTEDTYPEWRAPPER_TYPEMAP, _NESTEDTYPEWRAPPER_TYPECONTAINER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=887,
)

_NESTEDTYPEWRAPPER_TYPELIST.fields_by_name['nested_types'].message_type = _NESTEDTYPEWRAPPER
_NESTEDTYPEWRAPPER_TYPELIST.containing_type = _NESTEDTYPEWRAPPER
_NESTEDTYPEWRAPPER_TYPETUPLE.fields_by_name['nested_types'].message_type = _NESTEDTYPEWRAPPER
_NESTEDTYPEWRAPPER_TYPETUPLE.containing_type = _NESTEDTYPEWRAPPER
_NESTEDTYPEWRAPPER_TYPEMAP_NESTEDTYPESENTRY.fields_by_name['value'].message_type = _NESTEDTYPEWRAPPER
_NESTEDTYPEWRAPPER_TYPEMAP_NESTEDTYPESENTRY.containing_type = _NESTEDTYPEWRAPPER_TYPEMAP
_NESTEDTYPEWRAPPER_TYPEMAP.fields_by_name['nested_types'].message_type = _NESTEDTYPEWRAPPER_TYPEMAP_NESTEDTYPESENTRY
_NESTEDTYPEWRAPPER_TYPEMAP.containing_type = _NESTEDTYPEWRAPPER
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type'].message_type = _INPUTTYPEDESCRIPTOR
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_list'].message_type = _NESTEDTYPEWRAPPER_TYPELIST
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_tuple'].message_type = _NESTEDTYPEWRAPPER_TYPETUPLE
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_dict'].message_type = _NESTEDTYPEWRAPPER_TYPEMAP
_NESTEDTYPEWRAPPER_TYPECONTAINER.containing_type = _NESTEDTYPEWRAPPER
_NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container'].fields.append(
  _NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type'])
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type'].containing_oneof = _NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container']
_NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container'].fields.append(
  _NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_list'])
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_list'].containing_oneof = _NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container']
_NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container'].fields.append(
  _NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_tuple'])
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_tuple'].containing_oneof = _NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container']
_NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container'].fields.append(
  _NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_dict'])
_NESTEDTYPEWRAPPER_TYPECONTAINER.fields_by_name['nested_type_dict'].containing_oneof = _NESTEDTYPEWRAPPER_TYPECONTAINER.oneofs_by_name['nested_container']
_NESTEDTYPEWRAPPER.fields_by_name['nested_types'].message_type = _NESTEDTYPEWRAPPER_TYPECONTAINER
DESCRIPTOR.message_types_by_name['InputTypeDescriptor'] = _INPUTTYPEDESCRIPTOR
DESCRIPTOR.message_types_by_name['NestedTypeWrapper'] = _NESTEDTYPEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputTypeDescriptor = _reflection.GeneratedProtocolMessageType('InputTypeDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _INPUTTYPEDESCRIPTOR,
  __module__ = 'envisproto.execution.type_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:envisproto.execution.InputTypeDescriptor)
  ))
_sym_db.RegisterMessage(InputTypeDescriptor)

NestedTypeWrapper = _reflection.GeneratedProtocolMessageType('NestedTypeWrapper', (_message.Message,), dict(

  TypeList = _reflection.GeneratedProtocolMessageType('TypeList', (_message.Message,), dict(
    DESCRIPTOR = _NESTEDTYPEWRAPPER_TYPELIST,
    __module__ = 'envisproto.execution.type_wrapper_pb2'
    # @@protoc_insertion_point(class_scope:envisproto.execution.NestedTypeWrapper.TypeList)
    ))
  ,

  TypeTuple = _reflection.GeneratedProtocolMessageType('TypeTuple', (_message.Message,), dict(
    DESCRIPTOR = _NESTEDTYPEWRAPPER_TYPETUPLE,
    __module__ = 'envisproto.execution.type_wrapper_pb2'
    # @@protoc_insertion_point(class_scope:envisproto.execution.NestedTypeWrapper.TypeTuple)
    ))
  ,

  TypeMap = _reflection.GeneratedProtocolMessageType('TypeMap', (_message.Message,), dict(

    NestedTypesEntry = _reflection.GeneratedProtocolMessageType('NestedTypesEntry', (_message.Message,), dict(
      DESCRIPTOR = _NESTEDTYPEWRAPPER_TYPEMAP_NESTEDTYPESENTRY,
      __module__ = 'envisproto.execution.type_wrapper_pb2'
      # @@protoc_insertion_point(class_scope:envisproto.execution.NestedTypeWrapper.TypeMap.NestedTypesEntry)
      ))
    ,
    DESCRIPTOR = _NESTEDTYPEWRAPPER_TYPEMAP,
    __module__ = 'envisproto.execution.type_wrapper_pb2'
    # @@protoc_insertion_point(class_scope:envisproto.execution.NestedTypeWrapper.TypeMap)
    ))
  ,

  TypeContainer = _reflection.GeneratedProtocolMessageType('TypeContainer', (_message.Message,), dict(
    DESCRIPTOR = _NESTEDTYPEWRAPPER_TYPECONTAINER,
    __module__ = 'envisproto.execution.type_wrapper_pb2'
    # @@protoc_insertion_point(class_scope:envisproto.execution.NestedTypeWrapper.TypeContainer)
    ))
  ,
  DESCRIPTOR = _NESTEDTYPEWRAPPER,
  __module__ = 'envisproto.execution.type_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:envisproto.execution.NestedTypeWrapper)
  ))
_sym_db.RegisterMessage(NestedTypeWrapper)
_sym_db.RegisterMessage(NestedTypeWrapper.TypeList)
_sym_db.RegisterMessage(NestedTypeWrapper.TypeTuple)
_sym_db.RegisterMessage(NestedTypeWrapper.TypeMap)
_sym_db.RegisterMessage(NestedTypeWrapper.TypeMap.NestedTypesEntry)
_sym_db.RegisterMessage(NestedTypeWrapper.TypeContainer)


DESCRIPTOR._options = None
_NESTEDTYPEWRAPPER_TYPEMAP_NESTEDTYPESENTRY._options = None
# @@protoc_insertion_point(module_scope)
