theme: minima
title: RecoEdge Documentation
email: contact@nimbleedge.ai
description: > # this means to ignore newlines until "baseurl:"
  Updating soon.
# social links
github_username:  NimbleEdge # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage