# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envisproto/state/placeholder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envisproto.commons import id_pb2 as envisproto_dot_commons_dot_id__pb2
from envisproto.tensors import shape_pb2 as envisproto_dot_tensors_dot_shape__pb2
from envisproto.tensors import torch_tensor_pb2 as envisproto_dot_tensors_dot_torch__tensor__pb2
from envisproto.tensors import parameter_pb2 as envisproto_dot_tensors_dot_parameter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envisproto/state/placeholder.proto',
  package='envisproto.state',
  syntax='proto3',
  serialized_options=_b('\n\036ai.nimbleedge.envisproto.state'),
  serialized_pb=_b('\n\"envisproto/state/placeholder.proto\x12\x10\x65nvisproto.state\x1a\x1b\x65nvisproto/commons/id.proto\x1a\x1e\x65nvisproto/tensors/shape.proto\x1a%envisproto/tensors/torch_tensor.proto\x1a\"envisproto/tensors/parameter.proto\"\x83\x02\n\x0bPlaceholder\x12\x37\n\x0c\x63hild_tensor\x18\x01 \x01(\x0b\x32\x1f.envisproto.tensors.TorchTensorH\x00\x12\x38\n\x0f\x63hild_parameter\x18\x02 \x01(\x0b\x32\x1d.envisproto.tensors.ParameterH\x00\x12\"\n\x02id\x18\x03 \x01(\x0b\x32\x16.envisproto.commons.Id\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x31\n\x0e\x65xpected_shape\x18\x06 \x01(\x0b\x32\x19.envisproto.tensors.ShapeB\x07\n\x05\x63hildB \n\x1e\x61i.nimbleedge.envisproto.stateb\x06proto3')
  ,
  dependencies=[envisproto_dot_commons_dot_id__pb2.DESCRIPTOR,envisproto_dot_tensors_dot_shape__pb2.DESCRIPTOR,envisproto_dot_tensors_dot_torch__tensor__pb2.DESCRIPTOR,envisproto_dot_tensors_dot_parameter__pb2.DESCRIPTOR,])




_PLACEHOLDER = _descriptor.Descriptor(
  name='Placeholder',
  full_name='envisproto.state.Placeholder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='child_tensor', full_name='envisproto.state.Placeholder.child_tensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='child_parameter', full_name='envisproto.state.Placeholder.child_parameter', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='envisproto.state.Placeholder.id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='envisproto.state.Placeholder.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='envisproto.state.Placeholder.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expected_shape', full_name='envisproto.state.Placeholder.expected_shape', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='child', full_name='envisproto.state.Placeholder.child',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=193,
  serialized_end=452,
)

_PLACEHOLDER.fields_by_name['child_tensor'].message_type = envisproto_dot_tensors_dot_torch__tensor__pb2._TORCHTENSOR
_PLACEHOLDER.fields_by_name['child_parameter'].message_type = envisproto_dot_tensors_dot_parameter__pb2._PARAMETER
_PLACEHOLDER.fields_by_name['id'].message_type = envisproto_dot_commons_dot_id__pb2._ID
_PLACEHOLDER.fields_by_name['expected_shape'].message_type = envisproto_dot_tensors_dot_shape__pb2._SHAPE
_PLACEHOLDER.oneofs_by_name['child'].fields.append(
  _PLACEHOLDER.fields_by_name['child_tensor'])
_PLACEHOLDER.fields_by_name['child_tensor'].containing_oneof = _PLACEHOLDER.oneofs_by_name['child']
_PLACEHOLDER.oneofs_by_name['child'].fields.append(
  _PLACEHOLDER.fields_by_name['child_parameter'])
_PLACEHOLDER.fields_by_name['child_parameter'].containing_oneof = _PLACEHOLDER.oneofs_by_name['child']
DESCRIPTOR.message_types_by_name['Placeholder'] = _PLACEHOLDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Placeholder = _reflection.GeneratedProtocolMessageType('Placeholder', (_message.Message,), dict(
  DESCRIPTOR = _PLACEHOLDER,
  __module__ = 'envisproto.state.placeholder_pb2'
  # @@protoc_insertion_point(class_scope:envisproto.state.Placeholder)
  ))
_sym_db.RegisterMessage(Placeholder)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
